- hyrenweb/src/hrds/api/b/addScoure/AgentList.js
- hyrenweb/src/hrds/views/b/addScoure/AgentList.vue
- hyrenweb/src/hrds/views/b/loginNum1001/authorityManagement.vue
- hyrenweb/src/hrds/views/b/loginNum1001/dataSheetmain.vue
> agent的添加 删除 更改

- webFeatures/src/router/index.js
> 更改index.js   name

- webFeatures/src/css/common.css
- webFeatures/src/main.js
- webFeatures/src/view/Button/Button1.vue
- webFeatures/src/view/Table/zebrapattern.vue
> 添加css提取公共样式

- webFeatures/src/components/menu.js
- webFeatures/src/router/index.js
- webFeatures/src/view/DatePicker/DatePicker1.vue
- webFeatures/src/view/DatePicker/DatePicker2.vue
- webFeatures/src/view/DatePicker/DatePicker3.vue
- webFeatures/src/view/DatePicker/DatePicker4.vue
- webFeatures/src/view/Select/Select1.vue
> 修改select组件和日期组件

- vcol/src/css/common.css
> 添加默认表格鼠标划入样式class名

- vcol/src/css/common.css
> 添加公共样式class名

- hyrenweb/package-lock.json
- hyrenweb/src/hrds/b/addTask/addTask.vue
- hyrenweb/src/hrds/b/addTask/dataAcquisition.vue
- hyrenweb/src/hrds/b/addTask/sourceRegistration.vue
- hyrenweb/src/hrds/components/menu/menu.js
- hyrenweb/src/router/index.js
> 提交addtask组件1

- hyrenweb/src/hrds/b/addTask/addTask.vue
- hyrenweb/src/hrds/b/addTask/steps0.vue
- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps3.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/addTask/steps5.vue
- hyrenweb/src/hrds/components/menu/menu.js
- hyrenweb/src/router/index.js
> 改变addtask路由位置

- hyrenweb/src/hrds/b/agentList/agentList.vue
- hyrenweb/src/router/index.js
> 添加agentList

- hyrenweb/src/hrds/b/datasource/dataSheetmain.vue
- hyrenweb/src/hrds/b/datasource/datasource.js
- hyrenweb/src/hrds/b/datasource/datasource.vue
- hyrenweb/src/hrds/b/datasource/datasourceManagement.vue
- hyrenweb/src/hrds/components/menu/menu.js
- hyrenweb/src/router/index.js
> 实现数据源agent列表功能

- hyrenweb/src/hrds/b/agentList/agentList.vue
- hyrenweb/src/hrds/b/ftpCollect/ftpCollect.vue
- hyrenweb/src/hrds/b/unstructuredAgent/configureFileOption.vue
- hyrenweb/src/hrds/b/unstructuredAgent/configureStartMode.vue
- hyrenweb/src/router/index.js
> 添加非结构采集任务功能

- hyrenweb/src/hrds/b/addTask/addTask.js
- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps5.vue
- hyrenweb/src/utils/request.js
> 采集步骤二提交1206

- hyrenweb/src/assets/css/common.css
- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps3.vue
- hyrenweb/src/hrds/b/agentList/agentList.vue
> 修改删除提示1227

- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps3.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/addTask/steps5.vue
- hyrenweb/src/hrds/b/agentList/agentList.vue
> 修改agent列表样式

- hyrenweb/src/hrds/b/addTask/steps2.vue
> 修改数据库采集第二步

- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps5.vue
- hyrenweb/src/utils/request.js
> 采集步骤二自定义sql修改

- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps3.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/addTask/steps5.vue
- hyrenweb/src/hrds/b/agentList/agentList.vue
- hyrenweb/src/main.js
> 修改数据库采集代码项

- hyrenweb/src/hrds/b/addTask/step.vue
- hyrenweb/src/hrds/b/addTask/steps6.vue
> 修改数据库采集第六步完成

- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking.js
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip01.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip02.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip03.vue
> k部分内容提交0221

- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking.js
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip01.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip03.vue
> k树菜单提交0223

- hyrenweb/src/assets/css/common.css
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip01.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip02.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip03.vue
> k部分功能提交0225

- hyrenweb/src/assets/css/common.css
- hyrenweb/src/assets/images/loading-ball.svg
- hyrenweb/src/hrds/components/loading/index.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking.js
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip01.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip02.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip03.vue
- hyrenweb/src/utils/js/message.js
> k发布批量删除功能 0304

- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking.js
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip01.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip02.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip03.vue
> k搜索功能提交0305

- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking.js
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip01.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip02.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip03.vue
> k修改代码项接口0305

- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking.js
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip01.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip02.vue
- hyrenweb/src/hrds/k/dataBenchmarks/dataBenchmarking_tip03.vue
> k基础信息修改0309

- hyrenweb/src/hrds/k/tsb/tsb_result.vue
> 表结构结果点击提交修改

- hyrenweb/src/hrds/b/agentList/agentList.vue
- hyrenweb/src/hrds/b/dbAgentcollect/dbAgentcollect.js
- hyrenweb/src/hrds/b/dbAgentcollect/step1.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step2.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step3.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step4.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step6.vue
- hyrenweb/src/router/index.js
> db文件采集步骤串联

- hyrenweb/src/hrds/k/dataControl/ruleConfig/ruleConfig.vue
> By hll hyrenweb

- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps3.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/addTask/steps6.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step2.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step4.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step6.vue
> 数据库采集返回按钮增加

- hyrenweb/src/hrds/c/detailsPages/Monitor/relyJob/relyJob.vue
> 依赖作业已经问题修改

- hyrenweb/src/hrds/b/dbAgentcollect/step2.vue
> db文件采集步骤2更改

- hyrenweb/src/hrds/b/dbAgentcollect/step3.vue
> 文件采集3加dedid

- hyrenweb/src/hrds/b/dbAgentcollect/step1.vue
> 文件采集修改0424

- hyrenweb/src/hrds/c/detailsPages/Monitor/relyJob/relyJob.vue
> 依赖作业图已经问题修改

- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step3.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
> 采集问题修改0430

- hyrenweb/src/hrds/b/addTask/steps2.vue
> 修改采集自定义sql样式

- hyrenweb/src/hrds/c/detailsPages/Configure/etlDependency/etlDependency.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/etlJobDef/etlJobDef.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/resourcesAvailable/resourcesAvailable.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/resourcesUsage/resourcesUsage.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/subSystem/subSystem.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/systemParameter/systemParameter.vue
- hyrenweb/src/hrds/c/etlMage/etlMage.vue
> 作业调度已经问题样式修改

- hyrenweb/src/hrds/b/addTask/steps2.vue
> 数据库采集数据增量数

- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/addTask/steps6.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step3.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step6.vue
> 数据库采集修改0508

- hyrenweb/src/hrds/b/addTask/steps2.vue
> 数据库采集第二部选择列修改

- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps3.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
> 数据库第三步选择列修改

- hyrenweb/src/hrds/b/addTask/steps2.vue
> 数据库采集第二部修改全表查询

- hyrenweb/src/hrds/b/addTask/steps2.vue
> 数据库第二步修改1816

- hyrenweb/src/hrds/b/addTask/steps1.vue
> 数据库采集第一步编辑修改

- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
> 数据文件存储目的地修改

- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
- hyrenweb/src/utils/js/regular.js
> 文件采集目的地验证修改

- hyrenweb/src/hrds/c/etlMage/etlMage.vue
> 作业调度查看日志添加提示

- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
> 文件采集目的地默认值修改

- hyrenweb/src/hrds/b/dbAgentcollect/dbAgentcollect.js
- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step6.vue
> 数据文件增加目的地全表

- hyrenweb/src/hrds/b/dbAgentcollect/step3.vue
> 数据文件是否转存修改

- hyrenweb/src/hrds/c/detailsPages/Monitor/currentBatch/currentBatch.vue
- hyrenweb/src/hrds/c/etlMage/etlMage.vue
> 作业调度增加轮询 当前批量和监控信息

- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/addTask/steps6.vue
- hyrenweb/src/hrds/b/agentList/agentList.vue
- hyrenweb/src/hrds/b/agentList/taskLog.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step6.vue
> 修改数据库日志默认显示

- hyrenweb/src/hrds/h/market/addMartTable_1.vue
- hyrenweb/src/hrds/h/market/marketAction.js
- hyrenweb/src/hrds/k/dataControl/dataControl.js
- hyrenweb/src/hrds/k/dataControl/dataControl.vue
- hyrenweb/src/hrds/k/dataControl/mateDataManage/mateDataManage.vue
- hyrenweb/src/hrds/k/tsb/tsb.vue
> Hrsweb 5.0

- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/router/index.js
> 数据库采集修改parseint

- hyrenweb/src/hrds/c/detailsPages/Intervene/jobLevelIntervente/jobLevelIntervente.vue
> 更改作业调度作业批量干预

- hyrenweb/src/hrds/c/detailsPages/Intervene/jobLevelIntervente/jobLevelIntervente.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/currentJob/currentJob.vue
更改作业调度首页通过点击调度监控任务详情跳转报错问题，当前作业跳转作业干预报错问题
> 更改作业调度首页通过点击调度监控任务详情跳转报错问题，当前作业跳转作业干预报错问题

- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/addTask/steps6.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step3.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step4.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step6.vue
- hyrenweb/src/hrds/components/menu/index.vue
> 删除parseInt

- hyrenweb/src/hrds/b/semiStructuredAgent/collectFileOption.vue
- hyrenweb/src/hrds/b/semiStructuredAgent/collectOption.vue
- hyrenweb/src/hrds/b/semiStructuredAgent/semiStructuredAgent.js
- hyrenweb/src/hrds/c/detailsPages/Intervene/jobLevelIntervente/jobLevelIntervente.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/currentJob/currentJob.vue
- hyrenweb/src/router/index.js
> 半结构采集与之前作业调度更改

- hyrenweb/src/hrds/b/semiStructuredAgent/collectFileOption.vue
- hyrenweb/src/hrds/b/semiStructuredAgent/semiStructuredAgent.js
> 半结构化采集第二步文件设置

- hyrenweb/src/hrds/b/semiStructuredAgent/dataStorage.vue
- hyrenweb/src/hrds/b/semiStructuredAgent/semiStructuredAgent.js
> 半结构化数据存储页面添加

- hyrenweb/src/hrds/b/semiStructuredAgent/collectOption.vue
> 半结构采集添加is_sendok

- hyrenweb/src/hrds/b/addTask/steps4.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
> 提交采集文件启动修改

- hyrenweb/src/router/index.js
> index.js修改

- hyrenweb/src/hrds/h/market/detailMart.vue
- hyrenweb/src/router/index.js
> 更改indes.js添加详情信息显示头

- hyrenweb/src/hrds/h/market/addMarketIndex.vue
> 更改分类信息详情的左右样式

- hyrenweb/src/hrds/h/market/marketIndex.vue
> 新增集市分类信息保存

- hyrenweb/src/hrds/h/market/addMartTable_2.vue
- hyrenweb/src/hrds/h/market/marketIndex.vue
> 更改集市新增数据表样式

- hyrenweb/src/hrds/b/addTask/steps4.vue
> 数据库采集是否表头修改

- hyrenweb/src/router/index.js
> index.js添加表头显示信息

- hyrenweb/src/hrds/h/market/addMartTable_2.vue
> 配置表SQL，字段属性 工具台报错问题

- hyrenweb/src/hrds/b/dbAgentcollect/step1.vue
> 更改db文件新增分类无法输入

- hyrenweb/src/hrds/h/market/marketIndex.vue
> 更改分类添加编辑的树

- hyrenweb/src/hrds/h/market/marketIndex.vue
> 数据集市分类树结构更改

- hyrenweb/src/hrds/h/market/marketIndex.vue
> 更改集市分类新增编辑树结构

- hyrenweb/src/hrds/h/market/marketIndex.vue
> 更改集市新增编辑集市工程改变表格上级值

- hyrenweb/src/hrds/h/manage/version/marketVersionManage.vue
> 集市版本管理checkbox

- hyrenweb/src/router/index.js
> 更改数据集市为数据加工

- hyrenweb/src/hrds/h/market/marketIndex.vue
> 更新数据加工编辑完在新增出错问题

- hyrenweb/src/hrds/b/datasource/dataSheetmain.vue
> 更改1001编辑数据源验证

- hyrenweb/src/hrds/b/datasource/dataSheetmain.vue
> 更改1001编辑数据源编号验证

- hyrenweb/src/hrds/c/etlMage/etlMage.vue
> 作业调度部署加默认目录

- hyrenweb/src/hrds/c/detailsPages/Intervene/jobLevelIntervente/jobLevelIntervente.vue
- hyrenweb/src/hrds/c/detailsPages/Intervene/sysLevelIntervente/sysLevelIntervente.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/currentJob/currentJob.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/historyJob/historyJob.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/relyJob/relyJob.vue
- hyrenweb/src/hrds/c/etlMage/etlMage.vue
- hyrenweb/src/hrds/h/market/marketIndex.vue
> 更改作业调度message

- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
- hyrenweb/src/hrds/g/datarangemanage/dataRangeManage.vue
- hyrenweb/src/hrds/g/interfaceusemonitor/interfaceUseMonitor.vue
- hyrenweb/src/hrds/g/releasemanage/releaseManage.vue
- hyrenweb/src/hrds/g/usermanage/userManage.vue
> 修改数据库文件第五步查看详情11

- hyrenweb/src/hrds/b/dbAgentcollect/step1.vue
> 数据文件采集第一步设置分类点击任意单元格选中

- hyrenweb/src/hrds/b/addTask/addTask.js
- hyrenweb/src/hrds/b/addTask/dbcollect_2.vue
- hyrenweb/src/hrds/b/addTask/dbcollect_3.vue
- hyrenweb/src/hrds/b/addTask/steps1.vue
- hyrenweb/src/hrds/b/dbAgentcollect/step5.vue
- hyrenweb/src/utils/request.js
> 增加loading-立即启动2

- hyrenweb/src/hrds/b/dbAgentcollect/step6.vue
> 文件采集第六步loading修改

- hyrenweb/src/hrds/b/addTask/steps2.vue
- hyrenweb/src/hrds/b/addTask/steps3.vue
- hyrenweb/src/hrds/b/addTask/steps4.vue
> 修改采集问题height

- hyrenweb/src/hrds/b/datasource/datasource.vue
> 更改为新增数据库文件agent

- hyrenweb/src/hrds/b/dbAgentcollect/step2.vue
> db文件采集第二步提示添加

- hyrenweb/src/hrds/components/codemirror/index2.vue
- hyrenweb/src/utils/commons.js
> sql通过表名查询字段接口更改

- hyrenweb/src/hrds/b/agentList/agentList.vue
> 数据文件发送修改sql占位符

- hyrenweb/src/hrds/components/codemirror/index2.vue
- hyrenweb/src/hrds/h/market/addMartTable_2.vue
> 更改数据加工sql编辑时未更改

- hyrenweb/src/hrds/c/detailsPages/Configure/etlDependency/etlDependency.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/etlJobDef/etlJobDef.vue
> 作业调度作业依赖和作业添加页面跳转请求

- hyrenweb/src/hrds/l/selfAcess/access.vue
- hyrenweb/src/hrds/l/selfAcess/myAccess.vue
- hyrenweb/src/hrds/l/selfAcess/visualization.vue
> 2001数据可视化布局

- hyrenweb/src/hrds/l/selfAcess/visualization.vue
> 2001自主取数数据可视化

- hyrenweb/src/hrds/c/detailsPages/Configure/etlDependency/etlDependency.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/etlJobDef/etlJobDef.vue
- hyrenweb/src/hrds/c/detailsPages/Configure/resourcesUsage/resourcesUsage.vue
- hyrenweb/src/hrds/c/detailsPages/Intervene/jobLevelIntervente/jobLevelIntervente.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/currentJob/currentJob.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/historyJob/historyJob.vue
- hyrenweb/src/hrds/c/detailsPages/Monitor/relyJob/relyJob.vue
> 修改作业调度作业名称模糊查询

- hyrenweb/src/hrds/l/selfAcess/myAccess.vue
- hyrenweb/src/hrds/l/selfAcess/selfAcess.js
- hyrenweb/src/hrds/l/selfAcess/visualization.vue
- hyrenweb/src/hrds/l/selfAcess/visualizationindexlist.vue
> 自主取数已知问题修改

- hyrenweb/src/hrds/a/datastore/dataStoreAction.vue
> 更改已知问题数据存储层

- hyrenweb/src/hrds/a/datastore/dataStoreActionIndex.vue
> 更改数据存储层更新增加行问题

- hyrenweb/src/hrds/a/datastore/dataStoreActionIndex.vue
> 2001更改数据存储更新已知问题

- hyrenweb/src/hrds/l/selfAcess/visualization.vue
> 数据可视化话设置过滤条件，设置分组接口传参打印
